### ISSUE TITLE
Docker安装电脑关机重启之前的脚本定时任务全部丢失！

### ISSUE THREAD

**Issue by Dev-Wiki** [elecV2/elecV2P#173]
如题！

就这么设计的么？ 还是是个bug？ 每次重启都要重新添加？

**Comment by Dev-Wiki** [comment]
@elecV2

**Comment by elecV2** [comment]
重启前保存一下任务列表就不会丢失了。

建议每次修改任务列表都及时保存一下

**Comment by elecV2** [comment]
另外，如果Docker 运行没有使用持久化存储目录映射，在重启后数据也会丢失

**Comment by Dev-Wiki** [comment]
> 另外，如果Docker 运行没有使用持久化存储目录映射，在重启后数据也会丢失

那就是和保存无关了 就是docker 没有持久化的原因了

**Comment by Dev-Wiki** [comment]
> 另外，如果Docker 运行没有使用持久化存储目录映射，在重启后数据也会丢失

docker compose 如下：
```yml
version: '3.7'
services:
  elecv2p:
    image: elecv2/elecv2p
    container_name: elecv2p
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8100:80"
      - "8101:8001"
      - "8102:8002"
    volumes:
      - "/elecv2p/JSFile:/usr/local/app/script/JSFile"
      - "/elecv2p/Lists:/usr/local/app/script/Lists"
      - "/elecv2p/Store:/usr/local/app/script/Store"
      - "/elecv2p/Shell:/usr/local/app/script/Shell"
      - "/elecv2p/rootCA:/usr/local/app/rootCA"
      - "/elecv2p/efss:/usr/local/app/efss"
```
